<a href="https://colab.research.google.com/github/vvtrip/ml_manifestations/blob/master/17_DL/1_Neural_Networks_and_Deep_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Matrices and operations

In [1]:
# behind the scenes of Min max scaler

import numpy as np
from sklearn.preprocessing import MinMaxScaler

#generating 50 random data points between 1 to 200
np.random.seed(20)
data = np.random.randint(1,200, 50)
print('data\n',data)

def normalize(data):

  max_val = np.max(data)

  min_val = np.min(data)

  return np.divide(data - min_val, max_val - min_val)

X_norm = normalize(data)
print('\n',X_norm)

print('\n', list(MinMaxScaler().fit_transform(data.reshape(-1, 1))))

data
 [100  16 157 138 149  76  23  72 163 119  41  27  17 191 145 106 102   8
   7  27 142 187  26 132  62  84 186 111  33  11   7  76  19   4 146  44
 145  19  80 188  76 119 158 174   7 192  79  25 147  94]

 [0.5106383  0.06382979 0.81382979 0.71276596 0.7712766  0.38297872
 0.10106383 0.36170213 0.84574468 0.61170213 0.19680851 0.12234043
 0.06914894 0.99468085 0.75       0.54255319 0.5212766  0.0212766
 0.01595745 0.12234043 0.73404255 0.97340426 0.11702128 0.68085106
 0.30851064 0.42553191 0.96808511 0.56914894 0.15425532 0.03723404
 0.01595745 0.38297872 0.07978723 0.         0.75531915 0.21276596
 0.75       0.07978723 0.40425532 0.9787234  0.38297872 0.61170213
 0.81914894 0.90425532 0.01595745 1.         0.39893617 0.11170213
 0.7606383  0.4787234 ]

 [array([0.5106383]), array([0.06382979]), array([0.81382979]), array([0.71276596]), array([0.7712766]), array([0.38297872]), array([0.10106383]), array([0.36170213]), array([0.84574468]), array([0.61170213]), array([0.19680851]

In [10]:
a = np.array([[1,2],[3,4]])
print("matrix a dimension ", a.shape)

b = np.array([[5,6,7],[8,9, 10]])
print("matrix b dimension ", b.shape)

# The dot product greatly reduces the computation time especially when we have a large number of independent equations to solve.c
c = np.dot(a,b)
print("dot product of a and b stroing in c: \n", c)
print("matrix c dimension ", c.shape)

d = np.array([[1,2],[3,4]])
e = np.multiply(a,d)

f = a * d
print('elementwise product of a and d storing in e: \n', e)
print("matrix e dimension ", e.shape)

print('elementwise product of a and d storing in f: \n', f)
print("matrix e dimension ", f.shape)

matrix a dimension  (2, 2)
matrix b dimension  (2, 3)
dot product of a and b stroing in c: 
 [[21 24 27]
 [47 54 61]]
matrix c dimension  (2, 3)
elementwise product of a and d storing in e: 
 [[ 1  4]
 [ 9 16]]
matrix e dimension  (2, 2)
elementwise product of a and d storing in f: 
 [[ 1  4]
 [ 9 16]]
matrix e dimension  (2, 2)


**BROADCASTING**

- NumPy operations are carried out on pairs of arrays (or vectors) on an element-by-element basis. Thus it is important that dimensions of two arrays must be same (or for dot product the inner dimension should match).

- This constraint is relaxed in Python when one of the matrices is of shape (m x n). The other one has to be of a shape (1 x n) or (m X 1) or just a scalar number.

  - When it is (1 x n) matrix (row vector), then it gets replicated itself column-wise to become (m x n) matrix.

  - When it is (m x 1) matrix (column vector), it gets replicated row-wise to become (m x n) matrix.

  - If it is a scalar number, then it gets converted to (m x n) matrix where each of the element is equal to the scalar number.

- Broadcasting also works when you want to apply the same function to each of the elements of a matrix or a vector. All you need to do is to just pass the matrix as an argument to the function.

In [16]:
#broadcasting example - (1 x n) matrix
a = np.array([[10, 10, 10], [20, 20, 20], [30, 30, 30]])
b = np.array([1, 2, 3])
c = a * b

print(c)

# additona of a matric and scaler
d = 1
print('\n',a + d)

# elementwise function call
def exp(x, n):
  return x ** n

print('\n', exp(a, 2))

[[10 20 30]
 [20 40 60]
 [30 60 90]]

 [[11 11 11]
 [21 21 21]
 [31 31 31]]

 [[100 100 100]
 [400 400 400]
 [900 900 900]]


In [27]:
A = np.array([[1,2,3], [4,5,6], [7,8,9]])
b = np.sum(A, axis= 0) #row wise, summing all row values and storing in corresponding column
print(A)
print()
print(b)
print(np.shape(b))
print()
print(A/b)
print()
print(A/b.reshape(1,3)) # b is already of shape (3,) and generates same result as  (1 x 3) but for certainity it is better to reshape explicitly

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[12 15 18]
(3,)

[[0.08333333 0.13333333 0.16666667]
 [0.33333333 0.33333333 0.33333333]
 [0.58333333 0.53333333 0.5       ]]

[[0.08333333 0.13333333 0.16666667]
 [0.33333333 0.33333333 0.33333333]
 [0.58333333 0.53333333 0.5       ]]


if a matrix has one dimension (m x 1) or (1 x m), it is called rank 1 matrix. If it has two dimensions of shape (m x n), where m > 1and n > 1, it's called rank 2 matrix. In general, if a matrix has n dimensions, it's called rank n matrix.

In [28]:
array1d = np.array([1,2,3,4])
print("shape of array1d before reshaping: ", array1d.shape)
array1d = array1d.reshape(1,4)
print("shape of array1d after reshaping: ", array1d.shape)
#rank of matrix can be found using np.linalg.matrix_rank() function
print("array1d is a martrix of rank {}".format(np.linalg.matrix_rank(array1d)))

shape of array1d before reshaping:  (4,)
shape of array1d after reshaping:  (1, 4)
array1d is a martrix of rank 1
